### ISSUE TITLE
Bookmark bar bug

### ISSUE THREAD

**Issue by 3demax** [Milly/compact_menu_2#10]
Menubar shows itself after adding a bookmark at first time only (after Firefox start) by clicking on "star" button in url box twice (for adding tags).
Have to uncheck Menu Bar again to close.
Next times menu bar does not show.

Happens with Firefox 4.0b7, Compact Menu 2 4.0

**Comment by gnud** [comment]
In version 3.6.12 and Compact menu 2 4.0 has the exact problem, whenever I press control + d to bookmark something, the menu gets visible and I have to manually uncheck it afterwards.

This happens only the first time I press control + d.

**Comment by pbhj** [comment]
Same for me both with 3.6.13 and 4.0b9pre. Though I get the impression that it's more random than being simply the first time a bookmark is added after loading Firefox.

I'm using Kubuntu 10.10 (maverick).
