### ISSUE TITLE
Compact Menu 2 stopped working on Firefox 3.7a4

### ISSUE THREAD

**Issue by pablox-cl** [Milly/compact_menu_2#2]
I was using this cool add-on on Firefox 3.6.3 without issues... I just starting using the developer preview and in the beggining the compact menu was working but suddenly it just stopped. The compact menu icon stopped appearing and it isn't in the "customize" dialogue either.

I tried to uninstall, re-installing, deleting the addon folder, etc.

**Comment by Milly** [comment]
Fix it on 3.2.0a
