### ISSUE TITLE
Use just the word 'Menu' as an icon, without having to create a custom one

### ISSUE THREAD

**Issue by tanstaafl** [Milly/compact_menu_2#26]
Hello,

I'm a long time user of the TinyMenu Addon, and I really like the way the 'TinyMenu' addon uses just the word 'Menu' instead of an icon...

I recently decided I wanted to switch to Tabs in the Titlebar,  but tinyMenu doesn't allow me to move the 'Menu' to the Navigation toolbar, so I started looking for alternatives, and found Compact Menu.

I really like it, but, I much prefer just the word 'Menu' instead of the icon.

I know I could create an icon myself, but I want to change from TinyMenu to Compact Menu on about 6o workstations, and I really don't want to have to maintain a custom icon for everyone... so...

Any chance for a simple option to choose either the current icon, the word 'Menu', or use a custom icon?

Thx for your consideration...

Charles

**Comment by Milly** [comment]
CompactMenu has these toolbar items:
- CompactMenu icon (blue earth)
- "Menu" menubar
- CompactBookmark icon
- "Bookmark" menubar

You can use `"Menu" menubar` by toolbar customize.
![compactmenu2-toolbarcustomize](https://cloud.githubusercontent.com/assets/22977/2655717/52ca3ee2-bfea-11e3-9797-4da9393cf27b.png)

Or, can customize icon by addon's option.
![compactmenu2-option](https://cloud.githubusercontent.com/assets/22977/2655719/5879c9a2-bfea-11e3-8928-0ab3bcd1ed9e.png)

**Comment by tanstaafl** [comment]
On 4/9/2014 9:26 AM, Milly notifications@github.com wrote:

> You can use |"Menu" menubar| by toolbar customize.

Ah, perfect!!

Thanks!
