### ISSUE TITLE
Latest version of CM2 not compatible with latest version of Tb

### ISSUE THREAD

**Issue by dotancohen** [Milly/compact_menu_2#3]
When using the compact_menu_2-3.1.1-fx_tb_sb_sm.xpi on a default Thunderbird 3.1 build for Linux, Tb throws an error:
"""
Compact Menu 2 3.1.1 could not be installed because it is not compatible with Thunderbird 3.1
"""

**Comment by Milly** [comment]
Latest version of CM2 is 3.2.0a
It's already compatible with Thunderbird 3.1

**Comment by dotancohen** [comment]
Milly, that version does not appear on the downloads page:
http://github.com/Milly/compact_menu_2/downloads

**Comment by Milly** [comment]
Please install from https://addons.mozilla.org/thunderbird/addon/4550/ "Beta channel" at middle of page.
Sorry I'm lazy. ;)
