### ISSUE TITLE
Doesn't work in Firefox 4 beta

### ISSUE THREAD

**Issue by grebulon** [Milly/compact_menu_2#4]
They must have changed something in the menus, because all menu customization addons stopped working.
I tested with version:
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:2.0b1) Gecko/20100630 Firefox/4.0b1

**Comment by Milly** [comment]
Thx tested.
CM2 work in Fx 4.0b2pre. I update target-application's max-version.
